"""First migrate

Revision ID: 96028f411341
Revises: 
Create Date: 2021-11-13 10:48:39.137793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96028f411341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('text', sa.String(length=255), nullable=True))
    op.drop_column('quote_model', 'quote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('quote', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('quote_model', 'text')
    # ### end Alembic commands ###
